### PR TITLE
docs(readme): expand usage

### LINKED ISSUE #4: Usage unclear (from dotnet/cli#3239)
From https://github.com/dotnet/cli/issues/3239#issuecomment-278765223

> @liamdawson read about usage, but it's not really clear how does one take advantage of that. Could you please explain how to use such tool in a typical tool development cycle on local dev machine:
> 
> > tool edit -> tool build -> tool pack -> ??? -> client restore -> client build -> dotnet tool client\project\dir
>
> Thanks!

### PR DESCRIPTION
**Pull request by BrainCrumbz**
Closes #4

### CODE REVIEW

**Review by liamdawson — CHANGES_REQUESTED** [review]
One more thing is that there's a switch for the tool that makes it run a command every time it packs a new version. Any chance you could document that too? I'm asking you because it will probably save you time if you use it :)

**Comment by BrainCrumbz** [comment]
Not sure if/when we'll use that but no probs in documenting. Now... what about this switch? Where to find info about it? 

Or would you just like to add your description to this change?

**Comment by BrainCrumbz** [comment]
@liamdawson what about starting with merging this PR, so to improve docs anyway. And right after start worrying about the further switch?

Just our 2c!

**Comment by liamdawson** [comment]
Hey, sorry for taking so long to getting around to this. :)

**Pull request merged**
